### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by yvonnetse** [BraftonSupport/longscroll#1]
- [x] copy&paste theme options instead of upload file
- [x] page title for blog
- [x] mobile first css
- [x] color picker for color options in pages
- [x] add more color options, separating links and buttons
- [x] change out featherlight

**Comment by dking3876** [comment]
sort out form encoding for file upload

**Comment by yvonnetse** [comment]
I didn't separate the links and buttons, I think the link color and button background color should be the same.
